---
version: "3.0"
services:
  package:
    image: node:16.17.1
    user: "${UID:-node}:${GID:-node}"
    tty: "${TTY:-true}"
    working_dir: /build
    volumes:
      - ./:/build
    command: sh -c "
      npm install -d &&
      npm audit fix || true &&
      npm run build:lde"
    environment:
      WATCH_FILES: '${WATCH_FILES:-true}'
      DEBUG_BOOTING: '${DEBUG_BOOTING:-false}'

      DEBUG_COLORS: '${DEBUG_COLORS:-true}'
      NODE_ENV: '${NODE_ENV:-lde}'

      DEBUG: 'pm:*'
      SHELL: '/bin/sh'
